# training_stats_utils.py
# -----------------------------------------------------------
# Build the metadata dict (`kwargs`) that later gets pushed
# to the Hugging Face Hub via `Trainer.push_to_hub()` or logged
# as part of training statistics.
#
# Author: Auto-generated by ChatGPT
# -----------------------------------------------------------

from dataclasses import dataclass
from typing import Dict, Optional


def build_training_kwargs(model_args, data_args) -> Dict[str, str]:
    """
    Assemble the kwargs dict used for `create_repo` / `push_to_hub`.

    Parameters
    ----------
    model_args : ModelArgs
        Contains at least `model_name_or_path`.
    data_args : DataArgs
        Contains dataset identifiers.

    Returns
    -------
    Dict[str, str]
        A dictionary with keys like 'finetuned_from', 'tasks',
        'dataset_tags', 'dataset_args', 'dataset'.
    """
    kwargs: Dict[str, str] = {
        "finetuned_from": model_args.model_name_or_path,
        "tasks": "automatic-speech-recognition",
    }

    if data_args.dataset_name is not None:
        kwargs["dataset_tags"] = data_args.dataset_name

        if data_args.dataset_config_name is not None:
            kwargs["dataset_args"] = data_args.dataset_config_name
            kwargs["dataset"] = f"{data_args.dataset_name} {data_args.dataset_config_name}"
        else:
            kwargs["dataset"] = data_args.dataset_name

    return kwargs

